#!/bin/sh

# redirect stderr
exec 2>&1

# Run the command
exec {{ pkg.path }}/bkmrk/.venv/bin/gunicorn \
    -b {{ cfg.gunicorn.host }}:{{ cfg.gunicorn.port }} \
    -w {{ cfg.gunicorn.workers }} \
    {{ cfg.gunicorn.app_module }} 
