#!/bin/sh

# redirect stderr
exec 2>&1

cd {{ pkg.path }}/bkmrk

# Run the command
exec .venv/bin/gunicorn \
    -b {{ cfg.gunicorn.host }}:{{ cfg.gunicorn.port }} \
    -w {{ cfg.gunicorn.workers }} \
    {{ cfg.gunicorn.app_module }} 
