language: python

jobs:
  include:
    - stage: test
      # molecule requires python 2 to run :(
      python: 2.7
      script: >
        pip install pipenv &&
        pushd ansible &&
        pipenv install --two --dev &&
        make check &&
        make -C roles/habitat check &&
      python: 3.6
      script: >
        pip install pipenv &&
        pipenv install --three --dev &&
        make check &&
        make coverage &&
        pipenv run coveralls
    - stage: deploy
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          branch: master
