language: python
python:
    - "3.6"

install:
    - pip install pipenv
    - pipenv install --three --dev

script:
    - make check
    - make -C ansible check
    - make test

after_script:
    - make coverage
    - pipenv run codecov
    - pipenv run coveralls
