language: python

jobs:
  include:
    - stage: test
      - python: 2.7
        script: >
          pip install pipenv &&
          pushd ansible &&
          pipenv install --two --dev &&
          make check &&
          make -C roles/habitat check &&
          popd
      - python: 3.6
        script: >
          pip install pipenv &&
          pipenv install --three --dev &&
          make check &&
          make test
    - stage: coverage
      - python: 3.6
        script: >
          pip install pipenv &&
          pipenv install --three --dev &&
          make coverage &&
          pipenv run coveralls
