language: python
python:
    - "3.6"

install:
    - pip install pipenv
    - pipenv install --dev
    - pushd ansible && pipenv install && popd

script:
    - make check
    - make -C ansible check
    - make -C ansible/roles/habitat check
    - make test

after_script:
    - make coverage
    - pipenv run coveralls
