language: python
python:
    - "3.6"

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - pushd ansible
    - pipenv install --two
    - make check
    - make -C roles/habitat check
    - popd
    - pipenv install --three
    - make check
    - make test

after_script:
    - make coverage
    - pipenv run coveralls
