jobs:
  include:
    - stage: py2
      python: 2.7
      script: >
        pip install pipenv &&
        pushd ansible &&
        pipenv install --two --dev &&
        make check &&
        make -C ansible/roles/habitat check &&
        popd
    - stage: py3
      python: 3.6
      script: >
        pip install pipenv &&
        pipenv install --three --dev &&
        make check &&
        make test
    - stage: coverage
      python: 3.6
      script: >
        pip install pipenv &&
        pipenv install --three --dev &&
        make coverage &&
        pipenv run coveralls
