---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  check_sequence:
    - lint
    - syntax
verifier:
  name: testinfra
  lint:
    name: flake8
