---
- name: Converge
  hosts: all
  roles:
    - role: habitat
      become: true
      vars:
        habitat__packages:
          - name: core/nginx
        habitat__services:
          - name: core/nginx
