---
- name: enable habitat service
  systemd:
    name: "{{ habitat__service_name }}"
    enabled: true
    daemon_reload: true

- name: restart habitat service
  systemd:
    name: "{{ habitat__service_name }}"
    state: restarted
    daemon_reload: true

- name: ensure habitat service
  service:
    name: "{{ habitat__service_name }}"
    state: started
