---
- name: Add certbot ppa
  apt_repository:
      repo: "ppa:certbot/certbot"

- name: Update apt repo
  apt:
      update_cache: yes

- name: Install Packages
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
      - nginx
      - git
      - ufw
      - python3
      - python-pip
      - supervisor
      - python-certbot-nginx
      - htop

- name: Obtain ssl certs
  command: certbot --agree-tos -m beta.bkmrk@gmail.com -n --nginx -d beta.bkmrk.life
  register: certbot

- name: Print certbot stdout
  debug:
      msg: "{{ certbot.stdout }}"

- name: Print certbot stderr
  debug:
      msg: "{{ certbot.stderr }}"

- name: Test ssl cert renewal
  command: certbot renew --dry-run

- name: Pip install pipenv
  pip:
      name: pipenv

- name: Add bkmrk user
  user:
      name: bkmrk

- name: Delete existing bkmrk code
  file:
      path: /opt/bkmrk/
      state: absent

- name: Git checkout code
  git:
      repo: 'https://github.com/vicyap/bkmrk.git'
      dest: /opt/bkmrk/

- name: Chown /opt/bkmrk/ for bkmrk user
  file:
      path: /opt/bkmrk/
      owner: bkmrk
      group: bkmrk
      state: directory
      recurse: yes

- name: Make init
  make:
      chdir: '/home/bkmrk/bkmrk'
      target: init
  become: yes
  become_user: bkmrk

- name: Configure supervisor
  copy:
      remote_src: yes
      src: /opt/bkmrk/ansible/files/etc/supervisor/conf.d/bkmrk.conf
      dest: /etc/supervisor/conf.d/bkmrk.conf

- name: Configure nginx
  copy:
      remote_src: yes
      src: /opt/bkmrk/ansible/files/etc/nginx/sites-available/default
      dest: /etc/nginx/sites-available/default

- name: Verify nginx config
  command: nginx -t

- name: Set ufw rules
  ufw:
      rule: allow
      port: "{{ item }}"
  with_items:
      - ssh
      - http
      - https

- name: Set ufw rate limiting
  ufw:
      rule: limit
      port: ssh
      proto: tcp

- name: Enable ufw
  ufw:
      state: enabled

- name: Start nginx service
  service:
      name: nginx
      state: started
      enabled: true

- name: Start supervisor service
  service:
      name: supervisor
      state: started
      enabled: true

- name: Restart bkmrk supervisor service
  supervisorctl:
      name: 'bkmrk'
      state: restarted
